version: '3.8'

services:
  # Наш FastAPI бэкенд
  backend:
    build: ./backend
    container_name: ball_backend
    restart: always
    volumes:
      - ./backend/users.db:/app/users.db  # Сохраняем БД на хосте, чтобы данные не стирались
      - ./backend/static/uploads:/app/static/uploads # Сохраняем загруженные аватарки
    environment:
      - EMAIL_APP_PASSWORD=abcdefghijklmnop # Твой пароль приложения Gmail (по желанию)
    expose:
      - "8000"

  # Наш React фронтенд
  frontend:
    build: ./frontend
    container_name: ball_frontend
    restart: always
    expose:
      - "80"
    depends_on:
      - backend

  