version: '3.8'

services:
  # Наш FastAPI бэкенд
  backend:
    build: ./backend
    container_name: ball_backend
    restart: always
    volumes:
      - ./backend/data:/app/data
      - ./backend/static/uploads:/app/static/uploads
    environment:
      - EMAIL_APP_PASSWORD=abcdefghijklmnop
    ports:
      - "8000:8000"  # <-- ДОБАВЛЕНО! Бэкенд будет доступен на localhost:8000
    expose:
      - "8000"

  # Наш React фронтенд
  frontend:
    build: ./frontend  # <-- ВАЖНО: у вас папка ./frontend или ./frontend/my-react-app?
    container_name: ball_frontend
    restart: always
    ports:
      - "3000:80"  # <-- ИЗМЕНЕНО! Фронтенд будет доступен на localhost:3000
    depends_on:
      - backend