server {
    listen 80;
    server_name localhost;

    # 1. Запросы к API перенаправляем на FastAPI бэкенд
    location /api/ {
        proxy_pass http://backend:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 2. Интерактивную документацию Swagger тоже направляем на бэк
    location /docs {
        proxy_pass http://backend:8000/docs;
        proxy_set_header Host $host;
    }
    location /openapi.json {
        proxy_pass http://backend:8000/openapi.json;
        proxy_set_header Host $host;
    }

    # 3. Всё остальное отдаем фронтенду (React)
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Перенаправление всех запросов на index.html для работы React Router
        try_files $uri $uri/ /index.html;
    }

    # 4. Раздача статических файлов бэкенда (например, загруженные аватарки)
    location /static/ {
        proxy_pass http://backend:8000/static/;
        proxy_set_header Host $host;
    }
}